# Generated by Django 5.1.15 on 2026-09-29 14:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('student_id', models.CharField(help_text='University student ID number (e.g. 2023-01894-MN)', max_length=30, unique=True)),
                ('degree_program', models.CharField(help_text='e.g. BS Information Technology', max_length=100)),
                ('academic_year', models.CharField(help_text='e.g. 4th Year - Senior', max_length=50)),
                ('storage_quota_bytes', models.BigIntegerField(default=524288000, help_text='Storage quota in bytes (default 500 MB)')),
                ('avatar_initials', models.CharField(blank=True, help_text='2-letter initials for avatar display', max_length=4)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Student User',
                'verbose_name_plural': 'Student Users',
                'db_table': 'vault_student_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('DOCUMENT_UPLOAD', 'Document Upload'), ('DOCUMENT_DOWNLOAD', 'Document Download'), ('DOCUMENT_DECRYPT', 'Document Decrypt'), ('DOCUMENT_DELETE', 'Document Delete')], max_length=30)),
                ('details', models.TextField(help_text='Human-readable description of what happened')),
                ('document_title', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=30)),
                ('ip_address', models.GenericIPAddressField(default='0.0.0.0', help_text='Client IP address at the time of the action')),
                ('client_device', models.CharField(blank=True, help_text='User-Agent string from the client browser', max_length=255)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FLAGGED', 'Flagged')], default='SUCCESS', max_length=10)),
                ('user', models.ForeignKey(help_text='The student who performed the action', on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'vault_activity_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VaultDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Transcripts', 'Transcripts'), ('Certificates', 'Certificates'), ('Resumes', 'Resumes'), ('Identification Cards', 'Identification Cards'), ('Clearances', 'Clearances')], max_length=30)),
                ('original_filename', models.CharField(help_text='Original filename before encryption', max_length=255)),
                ('file', models.FileField(help_text='Encrypted file stored on disk', upload_to='vault_files/')),
                ('file_size_bytes', models.BigIntegerField(help_text='Size of the ORIGINAL plaintext file in bytes')),
                ('file_type', models.CharField(default='application/pdf', help_text='MIME type of the original file', max_length=100)),
                ('is_starred', models.BooleanField(default=False)),
                ('encryption_method', models.CharField(default='AES-256-GCM', editable=False, max_length=20)),
                ('checksum_sha256', models.CharField(help_text='SHA-256 hash of the ORIGINAL plaintext for integrity verification', max_length=64)),
                ('encryption_iv', models.BinaryField(help_text='AES-GCM 96-bit initialization vector (nonce)', max_length=12)),
                ('encryption_tag', models.BinaryField(help_text='AES-GCM 128-bit authentication tag', max_length=16)),
                ('issuing_authority', models.CharField(help_text='Institution or authority that issued the document', max_length=255)),
                ('academic_year', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(help_text='The student who owns this document', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vault Document',
                'verbose_name_plural': 'Vault Documents',
                'db_table': 'vault_document',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
